name: type_analyzer
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  analyzer:
  path: ^1.9.0
  code_builder: ^4.10.0
  dart_style:
  recase: ^4.1.0
  grammer: ^1.0.3
  collection: ^1.18.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
