name: frontend
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.2.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.0.1
  fluent_ui: ^4.8.3
  url_launcher: ^6.2.2
  cherry_toast: ^1.6.4

  http: ^1.1.2
  json_annotation: ^4.8.1
  provider: ^6.1.1
  meta: ^1.10.0
  get_it: ^7.6.4
  collection: ^1.18.0
  timeago: ^3.6.0
  fast_cached_network_image: ^1.2.0
  markdown_widget:
  appflowy_editor: ^2.2.0
  localstorage: ^4.0.1+4

dev_dependencies:
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - imgs/yaroo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
