name: blogdev

packages:
  - ./
  - frontend

command:
  bootstrap:
    runPubGetInParallel: false

scripts:
  build:frontend:
    run: |
      cd frontend && echo $APP_URL
      dart run build_runner build --delete-conflicting-outputs
      flutter build web --output=../public --release --web-renderer=html --dart-define Endpoint=$APP_URL
    packageFilters:
      flutter: true

  build:backend:
    run: |
      dart run build_runner build --delete-conflicting-outputs
      melos build:frontend
    packageFilters:
      flutter: false

  tests:
    run: |
      melos exec -c 1  -- "dart test" --fail-fast
    packageFilters:
      flutter: false

  format: melos exec -- "find . -name *.dart -not -name *.g.dart -exec "dart format {} --line-length=120 --set-exit-if-changed" \;"

  analyze: melos exec -- "dart analyze . --fatal-infos"
