name: blogdev

packages:
  - ./
  - frontend

command:
  bootstrap:
    runPubGetInParallel: false

scripts:
  build:frontend:
    run: |
      melos exec -c 1  -- "flutter build web --output=../public --release"
    packageFilters:
      flutter: true

  build:backend:
    run: |
      dart run build_runner build --delete-conflicting-outputs
      melos build:frontend
    packageFilters:
      flutter: false

  tests:
    run: |
      melos exec -c 1  -- "dart test" --fail-fast
    packageFilters:
      flutter: false

  tests:ci:
    run: |
      melos exec -c 1  -- "dart test --coverage=coverage" --fail-fast

  format: melos exec -- "dart format . --line-length=120"

  analyze: melos exec -- "dart analyze . --fatal-infos"
